apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tlz9j1ga0-python-gitops
  description: This is GitOps manifest for tlz9j1ga0-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=tlz9j1ga0-python
    backstage.io/kubernetes-id: tlz9j1ga0-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tlz9j1ga0-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tlz9j1ga0-python
