apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tlz9j1ga0-python
  janus-idp.io/tekton: tlz9j1ga0-python
  backstage.io/kubernetes-id: tlz9j1ga0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tlz9j1ga0-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
